name: Sync LeetCode

on:
  workflow_dispatch:

  schedule:
    # 11:00 AM IST
    - cron: "30 5 * * *"

    # 7:00 PM IST
    - cron: "30 13 * * *"

    # 11:00 PM IST
    - cron: "30 17 * * *"  # 11:00 PM IST

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true
          commit-header: "[LeetCode Sync]"
